#
#
#
#
Title:
  enable: true
  lineOne: "&7Hello &6%player_name%"
  lineTwo: "&7On the server"
Player:
  onJoin:
    teleportToSpawn: true
  changeGameMode:
    enable: true
    gamemode: ADVENTURE
customJoinMessage:
  enable: true
  owner:
    # nlobby.joinmessage.owner
    permission: "owner"
    chat:
      enable: true
      joinMessage: "&6&lN&e&lL &8| &cOwner &4%playerName% &c join the server!"
      quitMessage: "&6&lN&e&lL &8| &cOwner &4%playerName% &c quit the server!"
    ActionBar:
      enable: true
      onJoin:
        message: "&6&lN&e&lL &8| &cOwner &4%playerName% &c join the server!"
      onQuit:
        message: "&6&lN&e&lL &8| &cOwner &4%playerName% &c quit the server!"
World:
  voidTeleport: true
  spawn:
    worldName: ""
    x: ""
    y: ""
    z: ""
ItemOnJoin:
  0:
    itemName: ""
    item: COMPASS
    itemLore:
      - ""
      - ""
    itemCMD: ""
    interact: RIGHT_CLICK
CustomMessage:
